### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [evashchuk/kottans-js-2016-hw#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить
```html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```

**Comment by evashchuk** [comment]
https://github.com/evashchuk/kottans-js-2016-hw/blob/master/week01/hw1/habr.html

**Comment by mkozhukharenko** [comment]
you don't need to wrap a section in aside. https://github.com/evashchuk/kottans-js-2016-hw/blob/master/week01/hw1/habr.html#L10-L29
use either `div` or ..

**Comment by mkozhukharenko** [comment]
it should be outside a nav
https://github.com/evashchuk/kottans-js-2016-hw/blob/master/week01/hw1/habr.html#L45-L48
[here](http://html5doctor.com/nav-element/) is an explanation

**Comment by mkozhukharenko** [comment]
I would not put all this element inside an address 

```html
 <address class="article author">
    <figure>
      <img src="userphoto.png" alt="user photo">
      <figcaption>@rayproud</figcaption>
    </figure>
    <table>
      <tr>
        <td>карма</td>
        <td><meter min="0" max="100" value="2"></meter></td>
      </tr>
      <tr>
        <td>рейтинг</td>
        <td><meter min="0" max="100" value="0"></meter></td>
      </tr>
    </table>
    <ul>
      <li><a href="">Профиль</a></li>
      <li><a href="">Публикации</a></li>
      <li><a href="">Комментарии</a></li>
      <li><a href="">Избранное</a></li>
      <li><a href="">Подписчики</a></li>
    </ul>
  </address>
```

**Comment by mkozhukharenko** [comment]
the same issue: don't use a section || aside as a wrapper. 

https://github.com/evashchuk/kottans-js-2016-hw/blob/master/week01/hw1/habr.html#L191

**Comment by mkozhukharenko** [comment]
it's a subject of dispute but I would not use a table here 
https://github.com/evashchuk/kottans-js-2016-hw/blob/master/week01/hw1/habr.html#L58-L67
It's much harder to apply a styles to a table than to a simple divs

**Comment by mkozhukharenko** [comment]
without taking into account  that small issues it looks very good! 👍
