### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [evashchuk/kottans-js-2016-hw#5]
Generally ok, kudos for doing these as separated plugins
1. Prefer const over `let`, given most use cases you had are good fit for `const`, defining data once

2. ```
let clearClases = clases.filter(item => {
  if (item.startsWith('js-')) {
    jsClases += jsClases.length === 0 ? item.slice(3) : ' ' + item.slice(3);
  } else {
    return item;
  }
});
```
I would highly discourage from doing some side-effect logic inside `filter`.
Also, filter needs to return boolean. In here you return either nothing implicitly or not boolean explicitly.
Would not pass code review.


3. ```
let clearClases = clases.filter(item => {
     return !bootstrapReg.test(item);
   });
```   
Code-style preference thing, but could be `const clearClases = clases.filter(item => !bootstrapReg.test(item));`

4. ```
if (clearClases.length > 0) {
  node.attrs.class = clearClases.join(' ');
} else {
  node.attrs.class = null;
}
```
Matter of taste once again, but could be shorter using `?:`

**Comment by evashchuk** [comment]
Thanks for comments) I have made some changes.
